### ISSUE TITLE
CP map Issue

### ISSUE THREAD

**Issue by Saintzju** [noonchen/STDF-Viewer#104]
(1)CP show stack wafer map function, while now only can transfer one STDF file. can not support more STDF file read at the same time.
(2)CP bin percentage information may cover each other in the 3.4 version.

![image](https://user-images.githubusercontent.com/105335189/167765941-f5264754-6c20-4bbc-afd4-e68be0c76e90.png)

**Comment by noonchen** [comment]
Hi Saintzju,

Multi-file support is a considerably difficult task for now, since this is my part-time project, I don't think it would be possible for me to do at the moment. 

However, you can manually combine the STDF files into a single STDF file, then open it with STDF Viewer, it can easily achieved by python:
```python
stdf_path_list = ['path1', 'path2']
stdf_output = 'out_path'
data = b''

for p in stdf_path_list:
    with open(p, 'rb') as stdf:
        data += stdf.read()

with open(stdf_output, 'wb') as stdf:
    stdf.write(data)
```

As for the display issue, it may take some moments to fix, for it is a `matplotlib` issue.

**Comment by Saintzju** [comment]
> 

I find a merge STDF tool and code, may reference for you:

https://github.com/showjim/STDF-Edit-Tool

**Comment by noonchen** [comment]
> I find a merge STDF tool and code, may reference for you:
> 
> https://github.com/showjim/STDF-Edit-Tool

Same as the example code I provided. The difficulty is not how to merge stdf, it's how to implement the feature in the current architecture.

Thanks anyway.
