### ISSUE TITLE
V4.0.0 default low limit

### ISSUE THREAD

**Issue by Crazytommy90** [noonchen/STDF-Viewer#135]
Hi noochen:

Thanks for this project for the ATE test. When I load the same stdf file by using the version V4.0.0 and the version V3.4. The new version V4.0 have the result of "STDF-Viewer : WARNING : Default low limit can not be read...this should never happen". But the version V3.4 can working fine. could you share some idea for this issue of the new version. Thanks again.

Best Regards
Yang

**Comment by noonchen** [comment]
Hi Yang,

This error is related to this section of code:
https://github.com/noonchen/STDF-Viewer/blob/23c2bf8c80c6ced83aa28e08bd3abe160cba9237/deps/rust_stdf_helper/src/rust_functions.rs#L344-L353

When a new (test num, test name) combination is detected, its limits will be stored as the default limits, if PTRs of the same test are encountered in other DUTs, the code above will be executed and check whether limits are changed, at this point, the default limit should be stored already.

Since the coding language is changed, it might take some time to diff code changes. In the mean time, it would be helpful if you can send this file to my email for me to debug.

**Comment by Crazytommy90** [comment]
Hi noonchen,

Thanks for your informance clearfy. I will send out the file to you by using the email. 

Best Regards
Yang

**Comment by noonchen** [comment]
Hi Yang,

I've received your file. Turns out there is an issue in your file.

STDF-Viewer uses (test_num, test_name) as the identifier. However, (181000, "GOA_RONH") was used in both PTR and FTR record, it was not supported nor suggested.

It is recommended to use different test number for different test.

If it works in V3.4.0, then it should be a bug in the older version.

**Comment by Crazytommy90** [comment]
Hi noon,

already get the file work fine. thanks for the support. 

Best Regards
Yang
