### ISSUE TITLE
Low performance when parsing data & generate figures from Bzip compressed files

### ISSUE THREAD

**Issue by noonchen** [noonchen/STDF-Viewer#38]
It is because the module [`indexed_bzip2`](https://github.com/mxmlnkn/indexed_bzip2/issues/8) that used in STDF Viewer doesn't support random access, more precisely, backward seeking, without creating a full index.

**Comment by mxmlnkn** [comment]
I saw this linked issue. The new ParallelBZ2Decoder backend in indexed_bzip2 1.2.0 should be able to do backward seeking without any overhead. But it isn't yet the default, you actually will have to use more than one thread to make use of this backend, e.g.:

```python
self.std_handle = IndexedBzip2File(f, parallelization = 2)
```

Or, you can any parallelization you want. A parallelization of 1 will switch to the legacy decoder even though the parallel decoder would work with 1 decoder thread. The parallel backend is pretty new that's why I didn't make it the default right away but it should be stable. I threw a lot of tests and sanitizers at it.

I also added MinGW32 support in the `setup.py` but I did not actually test it, yet... Maybe you are lucky.

**Comment by noonchen** [comment]
Hi @mxmlnkn , sorry for the late response, I've tried 1.2.0 and it is significantly faster than 1.1.2! Really appreciate your great work!

There are some observations when I'm using the tool:

>But it isn't yet the default, you actually will have to use more than one thread to make use of this backend

Even I am not adding the argument `parallelization`, I do notice a performance improvement in 1.2.0, is it expected?

I wonder do you have any benchmark of how long would it take to do a random reading? Thanks in advance!

**Comment by mxmlnkn** [comment]
Sequential reading shouldn't have become much faster. That would be unexpected. But there are some improvements included in the update even for the old serial decoder backend, which might improve performance. For example, the Python glue layer [changed](https://github.com/mxmlnkn/indexed_bzip2/commit/35fab9947d3cc19582376d17b3d0f8af280e83a4) significantly. But I'm not sure whether this makes that much of a difference. I'll try to add some benchmarks to compare the version sometime in the future.
