### ISSUE TITLE
Error in Test Unit

### ISSUE THREAD

**Issue by ryanjmclaughlin** [noonchen/STDF-Viewer#78]
Getting an error when selecting a test.

![image](https://user-images.githubusercontent.com/212216/147667382-8fd19800-d7f5-47ae-9682-e068d9d3dc30.png)

**Comment by noonchen** [comment]
@ryanjmclaughlin 

I thought all the text fields in stdf files should be ACSII-encoded string...

Plz post the log content (About->Debug->Log) here to help me locate the issue code.

**Comment by noonchen** [comment]
@ryanjmclaughlin 
May I know which version you were used? Because it seems the utf-8 text is handled correctly in the latest version 3.3.0, although I am not intended to have utf-8 supported:

![image](https://user-images.githubusercontent.com/26359487/147855648-8bb12df9-3d84-47e1-bbb0-d264681b9422.png)

**Comment by vgrillot** [comment]
Hi Noonchen,

I had a similar issue with pyStdf lib. 
In europe we use '°C' for Celsius temperature. 
As the file is usually encoded as ASCII, it's ok to store '°' sign, wich is above 128. Using UTF-8 decoding will not match.
My solution was to decode UTF-8 by default, and in case of decoding error, falling back to ANSI (but it doesn't exists under linux) or Latin-8 page system.

Hope this helps,
Vincent.

**Comment by ryanjmclaughlin** [comment]
@noonchen Thanks for checking, I suspect you may be right on the ASCII per the standard, but Teradyne seems to allow it, so it is common in the STDF data I work with.

I captured the log, but it is blank, let me know if there is a way to capture more debug info for you.

`##### Log Content of [1] STDF-Viewer-2021-12-29.log Start #####
##### Log Content of [1] STDF-Viewer-2021-12-29.log End #####


##### Log Content of [2] STDF-Viewer-2022-01-03.log Start #####
##### Log Content of [2] STDF-Viewer-2022-01-03.log End #####

`

**Comment by noonchen** [comment]
@vgrillot Thanks for the info. 

I looked at the stdf v4 spec and the text field is defined as the char array in C (or byte array in python), which means there is no restriction on the text encoding since it is the encoded bytes that are written into the stdf file.

FYI, UTF-8 is compatible with ASCII, if bytes cannot be decoded into utf-8 string, it is negative for ASCII as well.

**Comment by noonchen** [comment]
@ryanjmclaughlin Sorry the error is not correctly logged. I guess I just know the root cause thanks @vgrillot mentioning `Latin` encoding.

The PTR info you posted shows `'\xb0C` is the value of the unit. Turns out it is a Latin-encoded string.
```
>>> b'\xb0C'.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

>>> b'\xb0C'.decode('latin')
'°C'
```
In python3, the default encoding is utf-8, and I just let python decode bytes for me, that's why ASCII and utf-8 text works just fine, but for other encodings (in this case, Latin) that are not compatible with utf-8, there will be an error.

I could add latin encoding support in the next patch, but I might not be able to handle all encoding types.

**Comment by ryanjmclaughlin** [comment]
@noonchen Sounds good, thanks!  Even if you don't want to support other encodings, an `errors='replace'` would at least prevent the decode error to ensure usability with odd encodings.

**Comment by vgrillot** [comment]
> @vgrillot Thanks for the info.
> FYI, UTF-8 is compatible with ASCII, if bytes cannot be decoded into utf-8 string, it is negative for ASCII as well.

You're right, I meant the "°" is stored as one byte but it's from ANSI table, or "latin-8" encoding.

**Comment by noonchen** [comment]
@ryanjmclaughlin Can you try these apps? They should fix this issue.

https://github.com/noonchen/STDF-Viewer/actions/runs/1652521164#Artifacts
