### ISSUE TITLE
Support for Zipped STDF

### ISSUE THREAD

**Issue by ryanjmclaughlin** [noonchen/STDF-Viewer#81]
Not sure if this is possible, but as a feature request, could you extend the GZ and BZIP to read regular ZIP STDF files?

**Comment by noonchen** [comment]
It depends. 

In order to support a new compressed format, I need a C library that contains following methods on a compressed file to build database:
1. `open`
2. `close`
3. `read`
4. `seek`
5. `tell`

A similar python module is also required, and `seek` operation must be fast otherwise the UI will become super laggy.

As for zip file, there are some C libraries and python modules that can deal with it, but I am to busy to give it a try recently :/ I might be able to take a look in the Spring Festival.

**Comment by noonchen** [comment]
Here are some updates about `zip` support.

`zip` is not like `gzip`, `bzip` format, it can 
- contain multiple files
- use multiple compression algorithm
- requires password if has one

my app reads one stdf file at a time, which means only one file in a zip can be read, others will be ignored;
zip with `DEFLATE` can be easily supported, thankfully it is the most popular zip;
I don't really want to support password, as it requires modifications on current api;

Under constrictions above, I managed to read `zip` compressed stdf and create a sqlite3 database successfully. 

However, things are not really smooth using python built-in module `zipfile`.
```python
offsets = list(range(0, int(1e6), 10)[::-1])

with open(path, "rb") as f:
    s = time()
    for o in offsets:
        f.seek(o)
    e = time()
    print("normal seek time: %f s\n" % (e-s))

with zipfile.ZipFile(zippath, "r") as zipobj:
    with zipobj.open(zipobj.namelist()[0], "r", force_zip64=True) as zfile:
        s = time()
        for o in offsets:
            zfile.seek(o)
        e = time()
        print("zip seek time: %f s\n" % (e-s))

# normal seek time: 0.080671 s
# zip seek time: 49.473239 s
```
`seek` time in the zip file is several hundreds times longer than the uncompressed file, this is not usable because this means users have to wait tens of seconds every time they click on test items.

Until there is a python module that support fast zip seek, I will mark this feature as experimental and not suggest to use zip format.

**Comment by noonchen** [comment]
The latest code on the main branch supports zip file (although only one file should be in the archive), the feature request is completed.

**Comment by ryanjmclaughlin** [comment]
Wow, you're amazing.  This is great, thank you!  Will test it out later this week.
