### ISSUE TITLE
support multiple PTR with same testnumber and different name 

### ISSUE THREAD

**Issue by thijaze** [noonchen/STDF-Viewer#91]
i like the tool very much your tool, it's really cool, but on main request if possible 
for PTR, we very often use the same "TEST_NUM" but with different  "TEST_TXT" , it much more easier to manage names on Test Program than numbers, especially if we have hundreds of tests from same type/sharing same limits
also, many of the modern tools already supports that option

seems that the current version stores PTRs according to its test numbers, thus it shows only 1 occurrence of the test

**Comment by noonchen** [comment]
@thijaze Thanks for your input, but I think sharing a common test number is off standard.

> Test Synopsis Record (TSR)
> 
> Contains the test execution and failure counts for **one** parametric or functional test in the test program. Also contains static information, such as test name. **The TSR is related to** the Functional Test Record (FTR), the Parametric Test Record (PTR), and the Multiple Parametric Test Record (MPR) **by test number**, head number, and site number.

According to the definition of TSR in the STDF V4 spec, the test number is used for identifying a test, where head number, site number is for differentiate statistics of test positions, meaning every test (FTR, PTR, MPR) should have a unique test number.

 ---
If we only talk about the possibility, the answer is not possible.

Changing the key from TestNum to (TestNum, TestName) is not a hard thing in python, but not easy in Cython or C. 

I have to build a database when user opens a file, there is a table that stores the dynamic limits for PAT-enabled PTRs, I can only use test number as the key, since I can only find a C dictionary implementation that accepts number as key.
https://github.com/noonchen/STDF-Viewer/blob/470fb6fb276b91048bb71efb9d083cde59632435/deps/cystdf/cystdf_amalgamation.pyx#L1106-L1107

I want to help you on this one, but for now, I don't think I can.

**Comment by thijaze** [comment]
Thanks a lot for the prompt and professional answer
i agree with you that it may be off standard but it is very common practice in the industry, especially for complex/large programs and in such cases we less care about the standard since tools usually follow the customer needs

if your only concern is limits - you can keep the same method as today because all of these tests that share the same test number have the same limits (we use one testlimit entry but changing test_text)

**Comment by noonchen** [comment]
Since it's a common practice, I'll put this in the feature list, as long as it doesn't conflict with the standards.

But this is not a small change, it will take a long time...

**Comment by thijaze** [comment]
Thanks a lot - appreciate much your support

**Comment by noonchen** [comment]
@thijaze I'm having some issues when associating TSR info with PTR by test number AND test name.

I created a unique test id for each (TEST_NUM, TEST_TXT) in PTR/FTR/MPR, so that the test different test name with same test number can have an individual entry.

However, TEST_NAM in TSR is not always the same as TEST_TXT in PTR, so that I cannot get test id from (TEST_NUM, TEST_NAM) in TSR, resulting in a mismatch.

I'd like to know what is the common practice in industry to link TSR with PTR/FTR/MPR?
